# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tei.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tei.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttei.proto\x12\x06tei.v1\"\xa0\x01\n\x08Metadata\x12\x15\n\rcompute_chars\x18\x01 \x01(\r\x12\x16\n\x0e\x63ompute_tokens\x18\x02 \x01(\r\x12\x15\n\rtotal_time_ns\x18\x03 \x01(\x04\x12\x1c\n\x14tokenization_time_ns\x18\x04 \x01(\x04\x12\x15\n\rqueue_time_ns\x18\x05 \x01(\x04\x12\x19\n\x11inference_time_ns\x18\x06 \x01(\x04\"\xdf\x01\n\x0c\x45mbedRequest\x12\x0e\n\x06inputs\x18\x01 \x01(\t\x12\x10\n\x08truncate\x18\x02 \x01(\x08\x12\x11\n\tnormalize\x18\x03 \x01(\x08\x12\x39\n\x14truncation_direction\x18\x04 \x01(\x0e\x32\x1b.tei.v1.TruncationDirection\x12\x18\n\x0bprompt_name\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ndimensions\x18\x06 \x01(\rH\x01\x88\x01\x01\x12\r\n\x05model\x18\x07 \x01(\tB\x0e\n\x0c_prompt_nameB\r\n\x0b_dimensions\"G\n\rEmbedResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x12\"\n\x08metadata\x18\x02 \x01(\x0b\x32\x10.tei.v1.Metadata\"\xe4\x01\n\x11\x45mbedBatchRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x10\n\x08truncate\x18\x02 \x01(\x08\x12\x11\n\tnormalize\x18\x03 \x01(\x08\x12\x39\n\x14truncation_direction\x18\x04 \x01(\x0e\x32\x1b.tei.v1.TruncationDirection\x12\x18\n\x0bprompt_name\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ndimensions\x18\x06 \x01(\rH\x01\x88\x01\x01\x12\r\n\x05model\x18\x07 \x01(\tB\x0e\n\x0c_prompt_nameB\r\n\x0b_dimensions\"_\n\x12\x45mbedBatchResponse\x12%\n\nembeddings\x18\x01 \x03(\x0b\x32\x11.tei.v1.Embedding\x12\"\n\x08metadata\x18\x02 \x01(\x0b\x32\x10.tei.v1.Metadata\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02*T\n\x13TruncationDirection\x12\x1e\n\x1aTRUNCATION_DIRECTION_RIGHT\x10\x00\x12\x1d\n\x19TRUNCATION_DIRECTION_LEFT\x10\x01\x32\x82\x01\n\x05\x45mbed\x12\x34\n\x05\x45mbed\x12\x14.tei.v1.EmbedRequest\x1a\x15.tei.v1.EmbedResponse\x12\x43\n\nEmbedBatch\x12\x19.tei.v1.EmbedBatchRequest\x1a\x1a.tei.v1.EmbedBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tei_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRUNCATIONDIRECTION']._serialized_start=840
  _globals['_TRUNCATIONDIRECTION']._serialized_end=924
  _globals['_METADATA']._serialized_start=22
  _globals['_METADATA']._serialized_end=182
  _globals['_EMBEDREQUEST']._serialized_start=185
  _globals['_EMBEDREQUEST']._serialized_end=408
  _globals['_EMBEDRESPONSE']._serialized_start=410
  _globals['_EMBEDRESPONSE']._serialized_end=481
  _globals['_EMBEDBATCHREQUEST']._serialized_start=484
  _globals['_EMBEDBATCHREQUEST']._serialized_end=712
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=714
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=809
  _globals['_EMBEDDING']._serialized_start=811
  _globals['_EMBEDDING']._serialized_end=838
  _globals['_EMBED']._serialized_start=927
  _globals['_EMBED']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
